- name: Add apt key for vscode
  tags: always, installation, vscode
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Add repository for vscode
  tags: always, installation, vscode
  apt_repository:
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
    filename: vscode
    state: present

- name: Install vscode package
  tags: always, installation, vscode
  apt:
    update_cache: true
    name: code
    state: present
