- name: Set user name
  become_user: "{{ base_user }}"
  tags: always, customization, git
  git_config:
    name: user.name
    scope: global
    value: ansible

- name: Set user email
  become_user: "{{ base_user }}"
  tags: always, customization, git
  git_config:
    name: user.email
    scope: global
    value: ansible@zrp.com.br
